--// Object Heirarchy File
--// Generated by Enetheru's Blender Export Script

cube_032 = {
	pieces = {
		cube_032_cube_034 = {
			offset = {-2.437, -19.254, -3.179},
		},
	},
	radius = 1.000,
	midpos = {-0.000, 0.000, 0.000},
	tex1 = "cube_032_tex1.dds",
	tex2 = "cube_032_tex1.dds",
	numpieces = 1,
	globalvertexoffsets = true,
	localpieceoffsets = false,

}
return cube_032