--// Object Heirarchy File
--// Generated by Enetheru's Blender Export Script

cube_023 = {
	pieces = {
		cube_023_cube_025 = {
			offset = {-29.164, 17.931, 34.534},
		},
	},
	radius = 1.000,
	midpos = {-0.000, 0.000, 0.000},
	tex1 = "cube_023_tex1.dds",
	tex2 = "cube_023_tex1.dds",
	numpieces = 1,
	globalvertexoffsets = true,
	localpieceoffsets = false,

}
return cube_023