--// Object Heirarchy File
--// Generated by Enetheru's Blender Export Script

cube_128 = {
	pieces = {
		cube_128_cube_153 = {
			offset = {4.668, 151.623, -6.505},
		},
	},
	radius = 1.000,
	midpos = {-0.000, 0.000, 0.000},
	tex1 = "cube_128_tex1.dds",
	tex2 = "cube_128_tex1.dds",
	numpieces = 1,
	globalvertexoffsets = true,
	localpieceoffsets = false,

}
return cube_128