--// Feature Definition File
--// Generated by Enetheru's Blender Export Script

local objectname = "cube_023"
local featureDef = {

--// General
	description = "",
	damage = 0.000,
	featureDead = "",
	flammable = false,
	noSelect = false,
	mass = 1.000,
	crushResistance = 0.000,

--// Visual
	object = "cube_023.obj",
	smokeTime = 300,

--// Reclaim & Resource
	reclaimable = true,
	autoReclaimable = true,
	reclaimTime = 0.000,
	metal = 0.000,
	energy = 0.000,
	resurrectable = -1,

--// Placement
	footprintX = 1,
	footprintZ = 1,
	blocking = true,
	upright = false,
	floating = false,

--// Collision Volumes
	collisionVolumeType = "box",
	collisionVolumeScales = {1.000, 1.000, 1.000},
	collisionVolumeOffsets = {0.000, 0.000, 0.000},
}
return lowerkeys({[objectname] = featureDef})
